{% set name = "xtensor-blas" %}
{% set version = "0.11.0" %}
{% set sha256 = "4a8186977d8f7b58a86347954048d3ea64d8b7b527ff049ebcb3b7c87f584263" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xtensor-blas/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [win and vc<14]
  # Skipping blas on windows since openblas is not available.
  # cf. https://github.com/conda-forge/openblas-feedstock/issues/2
  features:                     # [not win]
    - blas_{{ variant }}        # [not win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - xtensor >=0.16.0,<0.17.0
    - blas 1.1 {{ variant }}    # [not win]
    - openblas 0.2.20|0.2.20.*  # [not win]
  run:
    - xtensor >=0.16.0,<0.17.0
    - blas 1.1 {{ variant }}    # [not win]
    - openblas 0.2.20|0.2.20.*  # [not win]

test:
  commands:
    - test -f ${PREFIX}/include/xtensor-blas/xblas.hpp  # [unix]
    - test -f ${PREFIX}/share/cmake/xtensor-blas/xtensor-blasConfig.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/xtensor-blas/xtensor-blasConfigVersion.cmake  # [unix]
    # TODO: replace with %PREFIX%\Library with %LIBRARY_PREFIX%
    - if exist %PREFIX%\Library\include\xtensor-blas\xblas.hpp (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\Library\share\cmake\xtensor-blasConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\Library\share\cmake\xtensor-blasConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'BLAS extension to xtensor'
  description: 'xtensor-blas is an extension to the xtensor library, offering bindings to BLAS and LAPACK libraries through cxxblas and cxxlapack from the FLENS project.'
  doc_url: http://xtensor-blas.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor-blas

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
