travis:
  secure:
    BINSTAR_TOKEN: U6PVmt3EfRpddEBihkHamRvBtNTOJ6BpMF3rAo/5GFfpkWtMAgAKsZf57W1vKSK+4q1UcUSVIajDlFrLy8cpQiRBr3chL8UmxmzL5oPcDQ3xLpaS/7taQh2cKG+GejxNdJDYqP8MVRV4VJCw8aM36ZE87XqEV4TZdo2Bh5yJR8wVaYsaaswKzliAIMjSTjebMOXddP+VsKPfWe/RCFrruzRCVSx2+vwXsv9i+FwgM5LN5nkgnv2UW9J4whRBqkYb97U+FLmH3YUaZ3uk6zHySXa1pCg0+z97QVzsyYXnsC6gRQ0HPLMGo+9oSxcClIc2Z86/KPEMHpDsuCaSdzGXzuNFFXzO3eQKM09sV347d86noBYr7bCz34qkgHv6UJTFwcp8rBBmi+6Ui6rr6bwTGUipYsqVeQUWCFm8vrcq1hL4hZZM3LSQqIY0i51o3uM1mMwyTYG7+ygFXskibbPfxFouTZXEBKP4AMRRhvPL4eMwkWGT1Za+en8kphr1bAsM4+z6F2i95JKjyDUH9a8tKbOuT44iw+weUSz6YOxhMPpb3cEL4D4hnxunF3u7j+JUNkn3ns88g5C9w9rXED9ayoCmvtT6Dz8FOIJAWAwiJBPPq6zI2uk9B1szz1oNnBxfPP0qZoEwRfbb6dVkyukKGax+aV8/1sXjNKOWq44qulY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
