travis:
  secure:
    BINSTAR_TOKEN: ZdhWaVDmBHUzSBOMzNgWM2RJ8sk73nGZXphHUcoqGQqI6zFSdjUt28QfIE/ckZqJvJXdz1IVxsWVQcmn2beaT9zV+eBynauql3Jpzy07wcL+EpOL+2uKjBbvfX71rbwhddlMZ8jo7QamP7mK5+UcjrTMo1B22YdAz5wNxviJe4Bl+SLTa0SjxR7VKJE6kcboURnn7djw74SPFLiDUUc8f7ic4A9IWMJfPt+vyUlg+BKPRn5nKqsJemnz7azpGiKdzwmdzV2kaulCUiaucZHojP4JFGbYwi6f5dRyMlnbbjHtSo/bGKc5COQxu7AvVCc0C/RfEiMNBN3jV4f4ZTSktFjIakGOfH4YyIrcyR/6+2HeWILO5pLkC3gH4tPXtw2Nfyz6W6pF/abOC8LifVNrjK6lWKhw6GoN9u4e654C0MZDJbRjYQjTpokF2734Wy2toqxrNrzm9KDWb5dxR0ehkClsS0/GkbF+JasqSDPhIqf7KXSsdRA1njc5tLtJOQDtbubLutbozMKB5m3f6vINi2eIFyIhhWsWFa5OKc33ZBbbasNyrBX+onQam+bz+kSkPmogn1/jJoiocev1Oy706DwL2K+rueI03UH8pnUCKv82Jm5lGnhZLIH2/IBSTLiGoqsEBRYxM8ZafXHCEJJdkP02OnXn9uH7BIL1fXkmoVY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
